version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"